site_name: daamath

extra_css:
  - stylesheets/extra.css

nav:
  - index.md
  - implementations: 
    - implementations/index.md
    - python: 
      - implementations/python/index.md
    - c:
      - implementations/c/index.md
  - specification:
    - specification/index.md
    - functions:
      - specification/functions/index.md
      - arithmetic: specification/functions/arithmetic.md
      - trigonometry: specification/functions/trigonometry.md
      - logic: specification/functions/logic.md
      - interval: specification/functions/interval.md
      - quantize: specification/functions/quantize.md
    - strings: 
      - specification/strings/index.md
    - constants:
      - specification/constants/index.md
    - exceptions:
      - specification/exceptions/index.md
    - namespace: 
      - specification/namespace/index.md
      - aliases: specification/namespace/aliases.md

theme: 
  name: material
  features:
    - navigation.indexes
  palette:
#    scheme: slate
    primary: custom
    accent: custom


#theme: readthedocs

